---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    EntandoResourceKind: "EntandoPlugin"
    EntandoResourceNamespace: "my-namespace"
  name: "my-plugin-26174880"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "519b7fb6-c561-4b0a-8f22-cb54ae197b25"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-19T17:12:05Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "7353984"
  uid: "519b7fb6-c561-4b0a-8f22-cb54ae197b25"
lastTimestamp: "2021-06-19T17:12:05Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Fake\
  \ Controller Exception. Fix the root cause and then trigger a redeployment by adding\
  \ the annotation 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-plugin-8slx4-8-from-build-pack-v9-vgk8q"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
