---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    EntandoResourceKind: "EntandoPlugin"
    EntandoResourceNamespace: "my-namespace"
  name: "my-plugin-03383575"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "0b7ce46a-0e17-4d61-9c8c-861010549849"
action: "FAILED"
count: 1
firstTimestamp: "2021-07-01T08:12:06Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "2783628"
  uid: "0b7ce46a-0e17-4d61-9c8c-861010549849"
lastTimestamp: "2021-07-01T08:12:06Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Fake\
  \ Controller Exception. Fix the root cause and then trigger a redeployment by adding\
  \ the annotation 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-plugin-7bmn7-11-from-build-pack-2-rg6ph"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
