---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoPlugin: "my-plugin"
    EntandoResourceKind: "EntandoPlugin"
    EntandoResourceNamespace: "my-namespace"
  name: "my-plugin-95395550"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoPlugin"
    blockOwnerDeletion: true
    controller: true
    name: "my-plugin"
    uid: "c6655309-992c-4ab2-bf02-3782899532dc"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-21T16:36:00Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoPlugin"
  fieldPath: "status"
  name: "my-plugin"
  namespace: "my-namespace"
  resourceVersion: "7785195"
  uid: "c6655309-992c-4ab2-bf02-3782899532dc"
lastTimestamp: "2021-06-21T16:36:00Z"
message: "The deployment of EntandoPlugin my-namespace/my-plugin failed due to Test\
  \ Exception. Fix the root cause and then trigger a redeployment by adding the annotation\
  \ 'entando.org/processing-instruction: force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-plugin-fp28b-9-from-build-pack-dc-qnx47"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-plugin-controller"
type: "Error"
