---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "EntandoApp"
    EntandoResourceNamespace: "my-namespace"
    EntandoApp: "my-app"
  name: "my-app-63581812"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoApp"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "c8eeebb6-e7c2-4811-b7e0-961c3dff1307"
action: "FAILED"
count: 1
firstTimestamp: "2021-07-05T08:58:19Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoApp"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "6552716"
  uid: "c8eeebb6-e7c2-4811-b7e0-961c3dff1307"
lastTimestamp: "2021-07-05T08:58:19Z"
message: "The deployment of EntandoApp my-namespace/my-app failed due to Test Exception.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-app-con-c28jn-28-from-build-pack--g27b5"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-app-controller"
type: "Error"
