---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "EntandoApp"
    EntandoResourceNamespace: "my-namespace"
    EntandoApp: "my-app"
  name: "my-app-09610311"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoApp"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "c2a0cc42-3b08-47b4-88eb-0c9fc151f800"
action: "FAILED"
count: 1
firstTimestamp: "2021-07-05T10:46:13Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoApp"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "7825287"
  uid: "c2a0cc42-3b08-47b4-88eb-0c9fc151f800"
lastTimestamp: "2021-07-05T10:46:13Z"
message: "The deployment of EntandoApp my-namespace/my-app failed due to Test Exception.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-app-con-g7b9w-29-from-build-pack--c68v7"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-app-controller"
type: "Error"
