---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "EntandoApp"
    EntandoResourceNamespace: "my-namespace"
    EntandoApp: "my-app"
  name: "my-app-68868383"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoApp"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "bd908711-79c6-4fcf-97e9-7d680bacf996"
action: "FAILED"
count: 1
firstTimestamp: "2021-06-19T15:37:53Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoApp"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "984056"
  uid: "bd908711-79c6-4fcf-97e9-7d680bacf996"
lastTimestamp: "2021-06-19T15:37:53Z"
message: "The deployment of EntandoApp my-namespace/my-app failed due to Test Exception.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-app-con-wjxhw-20-from-build-pack--zddd5"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-app-controller"
type: "Error"
