---
apiVersion: "v1"
kind: "Event"
metadata:
  labels:
    EntandoResourceKind: "EntandoApp"
    EntandoResourceNamespace: "my-namespace"
    EntandoApp: "my-app"
  name: "my-app-25642055"
  namespace: "my-namespace"
  ownerReferences:
  - apiVersion: "entando.org/v1"
    kind: "EntandoApp"
    blockOwnerDeletion: true
    controller: true
    name: "my-app"
    uid: "bd4d1c6e-b25d-4734-890a-0203564bc04a"
action: "FAILED"
count: 1
firstTimestamp: "2021-07-01T11:00:29Z"
involvedObject:
  apiVersion: "entando.org/v1"
  kind: "EntandoApp"
  fieldPath: "status"
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "2441881"
  uid: "bd4d1c6e-b25d-4734-890a-0203564bc04a"
lastTimestamp: "2021-07-01T11:00:29Z"
message: "The deployment of EntandoApp my-namespace/my-app failed due to Test Exception.\
  \ Fix the root cause and then trigger a redeployment by adding the annotation 'entando.org/processing-instruction:\
  \ force'"
reason: "Failed"
related:
  apiVersion: "v1"
  kind: "Pod"
  name: "entando-k8s-entando-k8s-app-con-qfjkq-27-from-build-pack--nh94c"
  namespace: "controller-namespace"
source:
  component: "entando-k8s-app-controller"
type: "Error"
