---
apiVersion: "test.org/v1"
kind: "TestResource"
metadata:
  name: "my-app"
  namespace: "my-namespace"
  resourceVersion: "3897985"
  uid: "ee294af5-64c3-4e09-92a7-d6d8b4677c21"
spec:
  replicas: 1
status:
  serverStatuses:
    main: !<InternalServerStatus>
      qualifier: "main"
      type: "InternalServerStatus"
      started: "2021-06-07T10:21:49+0000"
      finished: "2021-06-07T10:21:49+0000"
      podPhases:
        my-app-dbprep-d567: "Failed"
      persistentVolumeClaimPhases:
        my-app-server-pvc: "Pending"
      entandoControllerFailure:
        failedObjectType: "TestResource"
        failedObjectName: "my-namespace/my-app"
        message: "Database preparation failed. Please inspect the logs of the pod\
          \ my-namespace/my-app-dbprep-d567"
        detailMessage: "org.entando.kubernetes.controller.spi.common.EntandoControllerException:\
          \ Database preparation failed. Please inspect the logs of the pod my-namespace/my-app-dbprep-d567\n\
          \tat org.entando.kubernetes.controller.support.command.DeployCommand.prepareDbSchemas(DeployCommand.java:220)\n\
          \tat org.entando.kubernetes.controller.support.command.DeployCommand.deployServiceInternally(DeployCommand.java:145)\n\
          \tat org.entando.kubernetes.controller.support.command.DeployCommand.lambda$execute$0(DeployCommand.java:103)\n\
          \tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\
          \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
          \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
          \tat java.base/java.lang.Thread.run(Thread.java:834)\n"
  phase: "failed"
crdName: "testresources.test.org"
